[EXPERIMENTAL] tinyfk backend
iory/scikit-robot pull request #182
Opened 2020-12-18 14:47 UTC by HiroIshida

2020-12-18 16:46 UTC, iory requested changes
It's a good function.
Please add docstrings for developers and users.

2020-12-18 16:46 UTC, iory commented on skrobot/planner/collision_checker.py
> +        return centers, coords_list, sphere_list, R
Please add `Returns` at this function's docstrings.

2020-12-18 16:46 UTC, iory commented on skrobot/planner/tinyfk_sqp_based.py
> +                               ):
Please add a docstring. It can be helpful for users.

2020-12-21 13:15 UTC, HiroIshida commented
@iory 
Let me give me some time to add documentation. I cannot decided the design completely, so is still to early to write the documentation. However, the as the example shows, the usage is completely same as the original one.

2020-12-21 14:03 UTC, iory commented
Sure!

2022-06-07 02:16 UTC, closed without merging