[NOW WRITING] Refactor sdf transform
iory/scikit-robot pull request #187
Opened 2020-12-23 06:53 UTC by HiroIshida

2020-12-23 15:11 UTC, iory requested changes

2020-12-23 15:11 UTC, iory commented on skrobot/coordinates/base.py
> +    def get_inverse(self):
inverse_transformation is better because Coordinates class is so.

2020-12-23 15:11 UTC, iory commented on skrobot/coordinates/base.py
> +    def __call__(self, pts):
Please add rotate_vector function.

2020-12-23 15:11 UTC, iory commented on tests/skrobot_tests/coordinates_tests/test_base.py
> +class testTransform(unittest.TestCase):
TestTransform

2020-12-24 00:31 UTC, HiroIshida commented
Fixed all points. I also change `__call__` to `transfrom_vector` to retain the name consistency with Coordinate class .

2020-12-24 03:56 UTC, iory approved these changes

2020-12-24 07:49 UTC, HiroIshida commented
rebased and ready to be merged!

2020-12-24 08:27 UTC, merged

2020-12-24 08:27 UTC, iory commented
LGTM!