[WIP] construct UnionSDF from RobotModel
iory/scikit-robot pull request #199
Opened 2020-12-30 09:50 UTC by HiroIshida

This PR implements a new constructor for `UnionSDF` that takes `RobotModel` as a parameter. This constructor enables directory convert `RobotModel` to `UnionSDF`. This feature is depends on my previous PR: https://github.com/iory/scikit-robot/pull/198

example 
```python
import skrobot
from skrobot.coo
rdinates.math import rotation_matrix_from_axis
from skrobot.model import Sphere
from skrobot.sdf import UnionSDF
import numpy as np

fetch = skrobot.models.Fetch()
fetch.reset_manip_pose()
union = UnionSDF.from_robot_model(fetch) # may take a lot in the first call due to sdf precomputation 
pts, _ = union.surface_points(n_sample=100)

viewer = skrobot.viewers.TrimeshSceneViewer(resolution=(641, 480))
viewer.add(fetch)
viewer.show()
for pt in pts:
    sp = Sphere(radius=0.01, pos=pt, color=[255, 0, 0, 200])
    viewer.add(sp)
```

![hoge](https://user-images.githubusercontent.com/38597814/103343393-4f0efc80-4acf-11eb-9bb5-5cfcf44875ec.png)

## TODO 
- [ ] write a test

2021-01-04 07:19 UTC, HiroIshida commented
nice that the PR is quickly merged! 
https://github.com/mikedh/trimesh/pull/1106
I will close https://github.com/iory/scikit-robot/pull/198 and fix this PR based on your PR

2021-01-04 14:43 UTC, HiroIshida commented
@iory I fixed the PR reflecting the update of trimesh. In `urdf.py` the information of origin (translation and rot) is removed and just made a new mesh. Thus, I added the origin information to the metadata of the each mesh. I still feel this method is kind of ad-hoc, but reasonable workaround. I want to here your opinion.

2021-01-04 23:43 UTC, iory requested changes

2021-01-04 23:43 UTC, iory commented on skrobot/sdf/signed_distance_function.py
> +    -------
Please add `-`.

2021-01-04 23:43 UTC, iory commented on skrobot/sdf/signed_distance_function.py
> +        dimension of the GridSDF
Is it only for `GridSDF`?

2021-01-04 23:43 UTC, iory commented on skrobot/sdf/signed_distance_function.py
> +    """convert Link to corresponding sdf
Please capitalize.

2021-01-04 23:43 UTC, iory commented on skrobot/sdf/signed_distance_function.py
> +                sdf = link2sdf(link, robot_model.urdf_path, dim_grid=50)
`dim_grid=dim_grid`

2021-01-04 23:43 UTC, iory commented on tests/skrobot_tests/test_sdf.py
> +        r2d2 = skrobot.models.urdf.RobotModelFromURDF(
Why did you use new model `r2d2`?

2021-01-05 04:55 UTC, HiroIshida commented
Fixed minor mistake in https://github.com/iory/scikit-robot/pull/199

dim_grid is only the parameter for GridSDF because other primitive's sdf can be computed analytically

the reason for adding r2d2 is that they have all primitives (fetch and PR2 are not). So testing that all primitive is properly converted to sdf, I need add new robot.

2021-01-05 05:03 UTC, iory commented
Where did you take the original r2d2 urdf?

2021-01-05 05:16 UTC, HiroIshida commented
Took from here: 
http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch
but I removed some mesh related elements stuff. 

But, I found that

2021-01-05 05:22 UTC, iory requested changes

2021-01-05 05:22 UTC, iory commented on skrobot/data/r2d2_description/r2d2.urdf
> +<robot name="materials">
Is name correct?

2021-01-05 05:29 UTC, HiroIshida commented
named is fixed to r2d2 in https://github.com/iory/scikit-robot/pull/199/commits/282cd9551589c1eb837cdcb93abe42b427f7499b

2021-01-05 05:32 UTC, iory commented
Hmm, the model is far from `r2d2`.
Does the main role of `r2d2` is for testing `Sphere`?

2021-01-05 05:37 UTC, HiroIshida commented
Its only for testing Sphere and Cylinder. It is also possible to make a model after loading the URDF, like, by associng and adding these primitives. However by this way, we cannot test the case when the mesh is transformed in the creation of urdf.

2021-01-05 06:04 UTC, iory commented
`Cylinder` and `Box` are contained by `PR2`. 
If you want to add `r2d2`, please make it more sophisticated. It's not `r2d2`.

2021-01-05 06:36 UTC, HiroIshida commented
I decided put the urdf file into the test directory as it will be used only in test and never be used by the user.

2021-01-05 06:39 UTC, iory requested changes

2021-01-05 06:39 UTC, iory commented on tests/skrobot_tests/primitives.urdf
> +<?xml version="1.0"?>
Please make skrobot_tests/data directory and put this in it.

2021-01-05 06:46 UTC, HiroIshida commented
Completed. (Sorry for directory writing in this comment box, somehow I cannot reply to the review...)

2021-01-05 06:49 UTC, iory requested changes

2021-01-05 06:49 UTC, iory commented on tests/data/primitives.urdf
> +<?xml version="1.0"?>
`tests/skrobot_tests/data/primitives.urdf`.

2021-01-05 07:17 UTC, iory approved these changes

2021-01-05 07:45 UTC, merged