Restrict pybullet version
iory/scikit-robot pull request #231
Opened 2021-04-16 07:45 UTC by HiroIshida

It is a temporally fix. 
Currently, after release v3.0.9 of pybullet, the pybullet module seems to be broken in python 2.7. https://pypi.org/project/pybullet/#history
So I restrict the version to be under v.3.0.8. h

2021-04-16 08:07 UTC, iory requested changes

2021-04-16 08:07 UTC, iory commented on setup.py
> +        'all': ['pybullet>=2.1.9, <3.0.8'],
How about writing as follows?
```
        'all': ['pybullet>=2.1.9;python_version>="3.0"',
                'pybullet>=2.1.9, <=3.0.8;python_version<"3.0"'],
```

2021-04-16 08:08 UTC, iory commented
OK. I understand the situation.

2021-04-16 08:26 UTC, HiroIshida commented on setup.py
> +        'all': ['pybullet>=2.1.9, <3.0.8'],
fix this.

2021-04-17 04:34 UTC, iory approved these changes

2021-04-17 04:34 UTC, merged